# This rule is not used by the project configmap-sync-controller itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over sync.conf-sync.com.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: configmap-sync-controller
    app.kubernetes.io/managed-by: kustomize
  name: configmapsyncer-admin-role
rules:
- apiGroups:
  - sync.conf-sync.com
  resources:
  - configmapsyncers
  verbs:
  - '*'
- apiGroups:
  - sync.conf-sync.com
  resources:
  - configmapsyncers/status
  verbs:
  - get
