# This rule is not used by the project configmap-sync-controller itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to sync.conf-sync.com resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: configmap-sync-controller
    app.kubernetes.io/managed-by: kustomize
  name: configmapsyncer-viewer-role
rules:
- apiGroups:
  - sync.conf-sync.com
  resources:
  - configmapsyncers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - sync.conf-sync.com
  resources:
  - configmapsyncers/status
  verbs:
  - get
