apiVersion: sync.conf-sync.com/v1alpha1
kind: ConfigMapSyncer
metadata:
  name: different-name-syncer
  namespace: default
spec:
  # Reference to the master ConfigMap
  masterConfigMap:
    name: source-config
    namespace: default

  # Target namespaces where the ConfigMap should be propagated
  targetNamespaces:
    - app1
    - app2
    - monitoring

  # Use a different name for target ConfigMaps
  targetConfigMapName: app-config

  # Merge strategy: Replace or Merge (default is Merge)
  mergeStrategy: Merge

  # Sync interval in seconds (default is 300)
  syncInterval: 3
