{{- if .Values.serviceAccount.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "configmap-sync-controller.fullname" . }}-manager-role
  labels:
    {{- include "configmap-sync-controller.labels" . | nindent 4 }}
rules:
- apiGroups:
  - sync.siemens.com
  resources:
  - configmapsyncers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - sync.siemens.com
  resources:
  - configmapsyncers/finalizers
  verbs:
  - update
- apiGroups:
  - sync.siemens.com
  resources:
  - configmapsyncers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "configmap-sync-controller.fullname" . }}-manager-rolebinding
  labels:
    {{- include "configmap-sync-controller.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "configmap-sync-controller.fullname" . }}-manager-role
subjects:
- kind: ServiceAccount
  name: {{ include "configmap-sync-controller.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "configmap-sync-controller.fullname" . }}-leader-election-role
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "configmap-sync-controller.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "configmap-sync-controller.fullname" . }}-leader-election-rolebinding
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "configmap-sync-controller.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "configmap-sync-controller.fullname" . }}-leader-election-role
subjects:
- kind: ServiceAccount
  name: {{ include "configmap-sync-controller.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }} 